# recreate with:
#   docker build -f etc/docker-conf/Dockerfile-base -t=pombase/web-base:v7 .
FROM bitnami/minideb:stretch
LABEL maintainer="Kim Rutherford <kim@pombase.org>"

RUN mkdir /downloads /pombase

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get -y update && apt-get -y dist-upgrade && apt-get clean
RUN apt-get -y install apt-utils curl gnupg2 git-core procps xz-utils \
  libterm-readline-gnu-perl pkg-config libssl-dev && apt-get clean
RUN cd /pombase && curl https://curation.pombase.org/software/solr-7.1.0.tar.xz | tar -x --xz -f - && \
    (cd /pombase/solr-7.1.0/; rm -rf example contrib licenses *.txt docs)

RUN apt-get -y install lsof jq gcc && apt-get clean
RUN apt-get -y install --reinstall python-pkg-resources && apt-get clean
RUN apt-get -y install python3-pip && apt-get clean
RUN apt-get -y install openjdk-8-jre-headless && apt-get clean
RUN apt-get -y install python3-zmq && apt-get clean
RUN pip3 install circus

RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN apt-get update && apt-get -y install nodejs && apt-get clean
RUN npm install --silent --unsafe-perm -g @angular/cli

WORKDIR /pombase

ENV DEBIAN_FRONTEND=interactive
