#!/bin/sh -

(curl -s -f http://localhost:8500/ && \
 curl -s -f 'http://localhost:8500/api/v1/dataset/latest/complete/ref/nov' \
   -H 'accept: application/json, text/plain, */*' | jq . | grep -i citation && \
 curl -s -f 'http://localhost:8500/api/v1/dataset/latest/complete/term/(molecular_function%20OR%20cellular_component)/enzyme%20binding' \
   -H 'accept: application/json, text/plain, */*' | jq . | grep -i 'binding to an enzyme' && \
 (curl -s -f 'http://localhost:8500/api/v1/dataset/latest/data/gene/SPAC20G4.09' | jq .;
  curl -s -f 'http://localhost:8500/api/v1/dataset/latest/data/gene/SJAG_00266' | jq .) | grep -i 'sensitive to latrunculin A' && \
 curl -s -f http://localhost:8983/ && \
 curl -s -f http://localhost:8999/motifsearch/ping/ || exit 1) > /dev/null
