# -*- dockerfile -*-
FROM pombase/web-base:v39
ARG version

LABEL maintainer="Kim Rutherford <kim@pombase.org>"

ARG target
ENV ANALYTICS_ID=UNSET
ENV APP_DEPLOY_CONFIG="{ mode: 'prod' }"

USER pombase

WORKDIR /pombase

COPY --chown=pombase:pombase pombase-chado-json /pombase/pombase-chado-json
RUN mkdir bin
RUN (cd pombase-chado-json; cargo build --release && cp target/release/pombase-server /pombase/bin/) && \
  rm -r /pombase/pombase-chado-json

USER root

RUN mkdir -p /var/www/html/api/v1/dataset/latest/; ln -s /pombase/jbrowse /var/www/html/jbrowse

COPY --chown=pombase:pombase web-json /var/www/html/web-json
COPY --chown=pombase:pombase gff /pombase/gff
COPY --chown=pombase:pombase chromosome_fasta /pombase/chromosome_fasta
COPY --chown=pombase:pombase feature_sequences /pombase/feature_sequences
RUN gzip -d /pombase/feature_sequences/*.gz

COPY --chown=pombase:pombase Rocket.toml /pombase/

COPY --chown=pombase:pombase pombase-python-web /pombase/pombase-python-web

COPY --chown=pombase:pombase pombase-config/website/pombase_v2_config.json /pombase/pombase_v2_config.json
RUN (cd /var/www/html/api/v1/dataset/latest; ln -s /var/www/html/web-json data)
RUN chown -R pombase:pombase /var/www/html

COPY --chown=pombase:pombase conf/solr-terms-schema-commands.txt /pombase/solr-terms-schema-commands.txt
COPY --chown=pombase:pombase conf/solr-refs-schema-commands.txt /pombase/solr-refs-schema-commands.txt

USER pombase

RUN cd ./solr-7.1.0/; ./bin/solr start -force -m 4g; \
    ./bin/solr create_core -force -c terms; \
    ./bin/solr create_core -force -c refs; \
    curl http://localhost:8983/solr/terms/config -d '{"set-user-property": {"update.autoCreateFields":"false"}}'; \
    curl http://localhost:8983/solr/refs/config -d '{"set-user-property": {"update.autoCreateFields":"false"}}'; \
    while read command; do curl -X POST -H 'Content-type:application/json' -d "$command" http://localhost:8983/solr/terms/schema; done < /pombase/solr-terms-schema-commands.txt; \
    while read command; do curl -X POST -H 'Content-type:application/json' -d "$command" http://localhost:8983/solr/refs/schema; done < /pombase/solr-refs-schema-commands.txt; \
    gzip -d < /var/www/html/api/v1/dataset/latest/data/solr_data/terms.json.gz | ./bin/post -c terms -type application/json -d && \
    gzip -d < /var/www/html/api/v1/dataset/latest/data/solr_data/references.json.gz | ./bin/post -c refs -type application/json -d && \
    ./bin/solr stop && \
    rm -rf /var/www/html/api/v1/dataset/latest/data/solr_data

COPY --chown=pombase:pombase ng-website /pombase/ng-website
RUN mkdir /pombase/.npm-global; npm config set prefix "/pombase/.npm-global"

ENV PATH="/pombase/.npm-global/bin:$PATH"

COPY --chown=pombase:pombase trackList.json /pombase/jbrowse/data/trackList.json
COPY --chown=pombase:pombase minimal_jbrowse_track_list.json /pombase/ng-website/minimal_jbrowse_track_list.json
COPY --chown=pombase:pombase pombase_jbrowse_track_metadata.csv /pombase/jbrowse/data/pombase_jbrowse_track_metadata.csv
COPY --chown=pombase:pombase GO.xrf_abbs /pombase/ng-website/

RUN (cd ng-website; ./etc/update_generated_files.sh GO.xrf_abbs /pombase/pombase_v2_config.json)

RUN (cd ng-website; ln -fs /pombase/pombase_v2_config.json .; \
     cp etc/update_vars.sh /pombase/ && \
     npm install -g yarn; \
     yarn; \
     ./etc/build_app.sh $target && cp -r dist/* /var/www/html/) && \
     rm -rf /pombase/ng-website /pombe/.npm-global

RUN (cd /var/www/html/jbrowse; \
    ./bin/prepare-refseqs.pl --fasta /pombase/chromosome_fasta/Schizosaccharomyces_pombe_all_chromosomes.fa.gz \
      --trackLabel 'DNA sequence' --key 'DNA sequence'; \
    ./bin/flatfile-to-json.pl --gff /pombase/gff/Schizosaccharomyces_pombe_all_chromosomes_forward_strand.gff3 \
      --maxLookback 9999999 --trackType CanvasFeatures --trackLabel 'PomBase forward strand features'; \
    ./bin/flatfile-to-json.pl --gff /pombase/gff/Schizosaccharomyces_pombe_all_chromosomes_reverse_strand.gff3 \
      --maxLookback 9999999 --trackType CanvasFeatures --trackLabel 'PomBase reverse strand features')

COPY --chown=pombase:pombase conf/circus.ini circus.ini
COPY --chown=pombase:pombase conf/start_all.sh start_all.sh
COPY --chown=pombase:pombase conf/docker-healthcheck docker-healthcheck

RUN (cd /var/www/html/jbrowse; ./bin/generate-names.pl)

RUN echo $version > $HOME/pombase_version

# for testing:
EXPOSE 8983
EXPOSE 8500
EXPOSE 8999

HEALTHCHECK --start-period=10s --interval=10s --timeout=20s --retries=10 \
  CMD /pombase/docker-healthcheck

CMD ./start_all.sh

