# recreate with:
#   docker build -f etc/docker-conf/Dockerfile-base -t=pombase/web-base:v18 .
FROM bitnami/minideb:stretch
LABEL maintainer="Kim Rutherford <kim@pombase.org>"

RUN mkdir /downloads /pombase

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get -y update && apt-get -y dist-upgrade && apt-get clean
RUN apt-get -y install apt-utils curl gnupg2 git-core procps xz-utils \
  libterm-readline-gnu-perl pkg-config libssl-dev unzip && apt-get clean
RUN apt-get -y install lsof jq gcc && apt-get clean
RUN apt-get -y install --reinstall python-pkg-resources && apt-get clean
RUN apt-get -y install python3-pip && apt-get clean
RUN apt-get -y install openjdk-8-jre-headless && apt-get clean
RUN apt-get -y install python3-zmq && apt-get clean
RUN pip3 install 'tornado<5'; pip3 install circus

RUN cd /pombase && curl http://oliver1.sysbiol.private.cam.ac.uk/software/solr-7.1.0.tar.xz | tar -x --xz -f - && \
    (cd /pombase/solr-7.1.0/; rm -rf example contrib licenses *.txt docs)

RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -
RUN apt-get update && apt-get -y install nodejs && apt-get clean
RUN npm install --silent --unsafe-perm -g @angular/cli
RUN apt-get -y install libperlio-gzip-perl libgd-perl

ENV JBROWSE_VERSION=1.12.4

RUN (cd /pombase; JBROWSE_TAR=JBrowse-$JBROWSE_VERSION-pombase.tar.gz; \
    curl -L http://oliver1.sysbiol.private.cam.ac.uk/software/$JBROWSE_TAR | tar xzf -; \
    mv JBrowse-$JBROWSE_VERSION-pombase jbrowse; \
    cd /pombase/jbrowse; ./setup.sh; rm -rf node_modules sample_data; \
    rm -rf /root/.cpan*)

WORKDIR /pombase

ENV DEBIAN_FRONTEND=interactive
