FROM pombase/pombase-base:v1
ARG version

LABEL maintainer="Kim Rutherford <kim@pombase.org>"

ARG target

#RUN chmod a+w /var/lock /var/run /var/log

WORKDIR /pombase

RUN mkdir bin; mkdir -p /var/www/html/api/v1/dataset/latest/
COPY latest_dump_dir /var/www/html/latest_dump_dir
RUN (cd /var/www/html/api/v1/dataset/latest; ln -s /var/www/html/latest_dump_dir/web-json data)

COPY ng-website /pombase/ng-website
COPY pombase-chado-json /pombase/pombase-chado-json

RUN (cd ng-website/frontend; ln -s /var/www/html/latest_dump_dir/pombe-embl/website/pombase_v2_config.json .)
RUN (cd ng-website/frontend && yarn install)
RUN (cd ng-website/frontend && ./etc/build_app.sh $target ../latest_dump_dir/ && cp -r dist/* /var/www/html/)

RUN (cd pombase-chado-json; cargo build --release && cp target/release/pombase-server /pombase/bin/)

RUN cd ./solr-6.6.0/; ./bin/solr start -force -m 10g; \
    ./bin/solr create_core -force -c terms -d basic_configs; \
    curl -X POST -H 'Content-type:application/json' --data-binary '{"add-field-type":{"name":"idField","class":"solr.StrField"}}' http://localhost:8983/solr/terms/schema; \
    curl -X POST -H 'Content-type:application/json' --data-binary '{"add-field-type":{"name":"textField","class":"solr.TextField","analyzer":{"type":"index","tokenizer":{"class":"solr.LowerCaseTokenizerFactory"},"filter":{"class":"solr.EdgeNGramFilterFactory","minGramSize":"2", "maxGramSize":"50"}}, "analyzer":{"type":"query", "tokenizer":{"class":"solr.LowerCaseTokenizerFactory"}}}}' http://localhost:8983/solr/terms/schema; \
    curl -X POST -H 'Content-type:application/json' --data-binary '{"add-field":{"name":"cv_name","type":"idField","indexed":"true","stored":"true"}}' http://localhost:8983/solr/terms/schema; \
    curl -X POST -H 'Content-type:application/json' --data-binary '{"add-field":{"name":"name","type": "textField","indexed":"true","stored":"true"}}' http://localhost:8983/solr/terms/schema; \
    curl -X POST -H 'Content-type:application/json' --data-binary '{"add-field":{"name":"definition","type":"textField","indexed":"true","stored":"true"}}' http://localhost:8983/solr/terms/schema; \
    find /var/www/html/api/v1/dataset/latest/data/solr_data/terms -name '*.json' | xargs ./bin/post -c terms; \
    ./bin/solr stop; \
    echo $version > $HOME/pombase_version

COPY conf/circus.ini circus.ini
COPY conf/httpd.conf pombase-apache2.conf

RUN a2enmod -q rewrite; a2enmod -q expires; a2enmod -q headers; \
  a2enmod -q proxy; a2enmod -q proxy_http; \
  cp ./pombase-apache2.conf /etc/apache2/sites-enabled/

CMD /usr/bin/circusd /pombase/circus.ini

EXPOSE 80

