FROM pombase/web-base:v9
ARG version

LABEL maintainer="Kim Rutherford <kim@pombase.org>"

ARG target
ENV ANALYTICS_ID=UNSET

WORKDIR /pombase

RUN mkdir bin; mkdir -p /var/www/html/api/v1/dataset/latest/; mkdir -p /var/www/html/latest_dump_dir
RUN ln -s /pombase/jbrowse-1.12.3-release /var/www/html/jbrowse

COPY pombase-chado-json /pombase/pombase-chado-json
ENV PATH="/root/.cargo/bin/:${PATH}"
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly; \
  rustup default nightly; \
  (cd pombase-chado-json; cargo build --release && cp target/release/pombase-server /pombase/bin/); \
  rm -r /root/.rustup /pombase/pombase-chado-json

COPY latest_dump_dir/web-json /var/www/html/latest_dump_dir/web-json
COPY latest_dump_dir/gff /var/www/html/latest_dump_dir/gff
COPY latest_dump_dir/fasta/chromosomes/Schizosaccharomyces_pombe_all_chromosomes.fa.gz /var/www/html/latest_dump_dir/Schizosaccharomyces_pombe_all_chromosomes.fa.gz
COPY latest_dump_dir/pombe-embl/website/pombase_v2_config.json /pombase/pombase_v2_config.json
RUN (cd /var/www/html/api/v1/dataset/latest; ln -s /var/www/html/latest_dump_dir/web-json data)

RUN cd ./solr-7.1.0/; ./bin/solr start -force -m 10g; \
    ./bin/solr create_core -force -c terms; \
    curl http://localhost:8983/solr/terms/config -d '{"set-user-property": {"update.autoCreateFields":"false"}}'; \
    curl -X POST -H 'Content-type:application/json' --data-binary '{"add-field-type":{"name":"idField","class":"solr.StrField"}}' http://localhost:8983/solr/terms/schema; \
    curl -X POST -H 'Content-type:application/json' --data-binary '{"add-field-type":{"name":"textField","class":"solr.TextField","analyzer":{"type":"index","tokenizer":{"class":"solr.LowerCaseTokenizerFactory"},"filter":{"class":"solr.EdgeNGramFilterFactory","minGramSize":"2", "maxGramSize":"50"}}, "analyzer":{"type":"query", "tokenizer":{"class":"solr.LowerCaseTokenizerFactory"}}}}' http://localhost:8983/solr/terms/schema; \
    curl -X POST -H 'Content-type:application/json' --data-binary '{"add-field":{"name":"cv_name","type":"idField","indexed":"true","stored":"true"}}' http://localhost:8983/solr/terms/schema; \
    curl -X POST -H 'Content-type:application/json' --data-binary '{"add-field":{"name":"name","type": "textField","indexed":"true","stored":"true"}}' http://localhost:8983/solr/terms/schema; \
    curl -X POST -H 'Content-type:application/json' --data-binary '{"add-field":{"name":"close_synonyms","type":"textField","multiValued":"true","indexed":"true","stored":"true"}}' http://localhost:8983/solr/terms/schema; \
    curl -X POST -H 'Content-type:application/json' --data-binary '{"add-field":{"name":"distant_synonyms","type": "textField","multiValued":"true","indexed":"true","stored":"true"}}' http://localhost:8983/solr/terms/schema; \
    curl -X POST -H 'Content-type:application/json' --data-binary '{"add-field":{"name":"interesting_parents","type": "textField","multiValued":"true","indexed":"true","stored":"true"}}' http://localhost:8983/solr/terms/schema; \
    curl -X POST -H 'Content-type:application/json' --data-binary '{"add-field":{"name":"definition","type":"textField","indexed":"true","stored":"true"}}' http://localhost:8983/solr/terms/schema; \
    find /var/www/html/api/v1/dataset/latest/data/solr_data/terms -name '*.json' | xargs ./bin/post -c terms > /dev/null; \
    ./bin/solr stop; rm -f /pombase/solr-7.1.0/server/logs/*; \
    rm -r /var/www/html/api/v1/dataset/latest/data/solr_data

COPY ng-website /pombase/ng-website
RUN (cd ng-website/frontend; ln -fs /pombase/pombase_v2_config.json .; \
     cp etc/update_analytics_id.sh /pombase/ && \
     npm install; \
     ./etc/build_app.sh $target && cp -r dist/* /var/www/html/) && \
     rm -rf /pombase/ng-website /usr/lib/node_modules

RUN (cd /var/www/html/jbrowse; \
    ./bin/prepare-refseqs.pl --fasta /var/www/html/latest_dump_dir/Schizosaccharomyces_pombe_all_chromosomes.fa.gz; \
    ./bin/flatfile-to-json.pl --gff /var/www/html/latest_dump_dir/gff/all_chromosomes.gff3 \
      --maxLookback 9999999 --trackType CanvasFeatures --trackLabel 'PomBase features')

COPY conf/circus.ini circus.ini
COPY conf/start_all.sh start_all.sh
COPY conf/trackList.json /var/www/html/jbrowse/data/trackList.json
RUN echo $version > $HOME/pombase_version

# for testing:
EXPOSE 8983
EXPOSE 8500

HEALTHCHECK --start-period=10s --interval=10s --timeout=20s --retries=10 \
  CMD curl -f http://localhost:8500/ && curl -f http://localhost:8983/ || exit 1

CMD ./start_all.sh

