#!/bin/sh -

# A script to make a Chado db from scratch using GMOD tools.  Must be
# run in the gmod-schema/chado directory.

if [ ! $# = 4 ]
then
  echo "$0: needs 4 arguments: db_name_suffix host username password" 1>&2
  exit 1
fi

export PERL5LIB=lib

replace() {
  var=$1
  new_val=$2
  file=$3
  perl -pne "s/$var=.*/$var=$new_val/" $file > $file.new
  mv $file.new $file
}

DB_NAME_SUFFIX=$1
HOST=$2
USER=$3
PASSWORD=$4

DB=pombase-chado-base-$DB_NAME_SUFFIX

echo "building database: $DB on $HOST"

replace CHADO_DB_NAME $DB $HOME/.gmod_profile
replace CHADO_DB_HOST $HOST $HOME/.gmod_profile
replace CHADO_DB_USER $USER $HOME/.gmod_profile
replace CHADO_DB_PASS $PASSWORD $HOME/.gmod_profile

replace DBNAME $DB build.conf
replace DBHOSE $HOST build.conf
replace DBUSER $USER build.conf
replace DBPASS $PASSWORD build.conf


#dropdb $DB; createdb $DB || exit 1

rm --verbose -rf tmp


(cd /var/pomcur/sources/pombe-embl/; svn update || exit 1)

echo update GO
(cd /var/pomcur/sources/go; cvs up)

perl Makefile.PL
make
make load_schema
make prepdb
make ontologies

echo PSI-MOD.obo
go2fmt.pl -p obo_text -w xml /var/pomcur/sources/PSI-MOD.obo | go-apply-xslt oboxml_to_chadoxml - > mod_obo_text.xml && stag-storenode.pl -d "dbi:Pg:dbname=$DB;host=$HOST" --user $USER --password $PASSWORD mod_obo_text.xml || exit 1

echo fypo_edit.obo
(cd /var/pomcur/sources/phenotype_ontology/; up) && go2fmt.pl -p obo_text -w xml /var/pomcur/sources/phenotype_ontology/fypo_edit.obo | go-apply-xslt oboxml_to_chadoxml - > phenotype_obo_text.xml && stag-storenode.pl -d "dbi:Pg:dbname=$DB;host=$HOST" --user $USER --password $PASSWORD phenotype_obo_text.xml || exit 1

echo fypo_extension_relations.obo
(cd /var/pomcur/sources/phenotype_ontology/; up) && go2fmt.pl -p obo_text -w xml /var/pomcur/sources/phenotype_ontology/supplemental_files/fypo_extension_relations.obo | go-apply-xslt oboxml_to_chadoxml - > phenotype_ex_rel_obo_text.xml && stag-storenode.pl -d "dbi:Pg:dbname=$DB;host=$HOST" --user $USER --password $PASSWORD phenotype_ex_rel_obo_text.xml || exit 1

echo go_annotation_extension_relations.obo
GET http://viewvc.geneontology.org/viewvc/GO-SVN/trunk/ontology/extensions/go_annotation_extension_relations.obo > /var/pomcur/sources/go_annotation_extension_relations.obo
go2fmt.pl -p obo_text -w xml /var/pomcur/sources/go_annotation_extension_relations.obo | go-apply-xslt oboxml_to_chadoxml - > anex_rel_obo_text.xml && stag-storenode.pl -d "dbi:Pg:dbname=$DB;host=$HOST" --user $USER --password $PASSWORD anex_rel_obo_text.xml || exit 1

echo pro_small.obo
go2fmt.pl -p obo_text -w xml /var/pomcur/sources/pro_small.obo | go-apply-xslt oboxml_to_chadoxml - > pro_small_obo_text.xml && stag-storenode.pl -d "dbi:Pg:dbname=$DB;host=$HOST" --user $USER --password $PASSWORD pro_small_obo_text.xml || exit 1

echo pombase_terms.obo
go2fmt.pl -p obo_text -w xml /var/pomcur/sources/pombase_terms.obo | go-apply-xslt oboxml_to_chadoxml > pombase_terms.xml && stag-storenode.pl -d "dbi:Pg:dbname=$DB;host=$HOST" --user $USER --password $PASSWORD pombase_terms.xml || exit 1

echo mini chebi.obo
go2fmt.pl -p obo_text -w xml /var/pomcur/sources/pombe-embl/mini-ontologies/chebi.obo | go-apply-xslt oboxml_to_chadoxml > chebi.xml && stag-storenode.pl -d "dbi:Pg:dbname=$DB;host=$HOST" --user $USER --password $PASSWORD chebi.xml || exit 1

echo mini cl.obo
go2fmt.pl -p obo_text -w xml /var/pomcur/sources/pombe-embl/mini-ontologies/cl.obo | go-apply-xslt oboxml_to_chadoxml > cl.xml && stag-storenode.pl -d "dbi:Pg:dbname=$DB;host=$HOST" --user $USER --password $PASSWORD cl.xml || exit 1

echo mini pato.obo
go2fmt.pl -p obo_text -w xml /var/pomcur/sources/pombe-embl/mini-ontologies/pato.obo | go-apply-xslt oboxml_to_chadoxml > pato.xml && stag-storenode.pl -d "dbi:Pg:dbname=$DB;host=$HOST" --user $USER --password $PASSWORD pato.xml || exit 1

echo mini PR.obo
go2fmt.pl -p obo_text -w xml /var/pomcur/sources/pombe-embl/mini-ontologies/pombe_mini_PR.obo | go-apply-xslt oboxml_to_chadoxml > mini-pr.xml && stag-storenode.pl -d "dbi:Pg:dbname=$DB;host=$HOST" --user $USER --password $PASSWORD mini-pr.xml || exit 1


echo populate cvtermpath

date; echo starting molecular_function
./bin/gmod_make_cvtermpath.pl -H $HOST -D $DB -d 'Pg' -u $USER -p $PASSWORD -c molecular_function
date; echo starting cellular_component
./bin/gmod_make_cvtermpath.pl -H $HOST -D $DB -d 'Pg' -u $USER -p $PASSWORD -c cellular_component
date; echo starting biological_process
./bin/gmod_make_cvtermpath.pl -H $HOST -D $DB -d 'Pg' -u $USER -p $PASSWORD -c biological_process
date; echo finished


echo make copies

for i in `seq 1 5`
do
  createdb -T $DB pombase-build-$DB_NAME_SUFFIX-v$i
done
